SELECT 
  ORD.ORDERID,
  CUS.CUSTOMERCODE,
  CUS.NAME1 CUS_NAME1,
  V.TASKID||'|'||V.ORDANALID||'|'||V.PICKINGTYPE LINEID,
  LOC.AISLE,
  LOC.BAY,
  LOC.LAYER,
  LOC.RELATIVEBAY,
  LOC.UNDEF7 PHYSICALBAY,
  (
    SELECT LISTAGG(COUNT(*),',') WITHIN GROUP (ORDER BY L.LAYER)
    FROM LOCATIONS L
    WHERE L.WAREHOUSEID=LOC.WAREHOUSEID
    AND L.STOREID=LOC.STOREID
    AND L.AISLE=LOC.AISLE
    AND L.UNDEF7=LOC.UNDEF7
    GROUP BY L.LAYER    
  ) COLUMNS_PER_LAYER,
  (
    SELECT COUNT(DISTINCT L.LAYER)||'-'||SUM(L.HEIGHT)
    FROM LOCATIONS L
    WHERE L.WAREHOUSEID=LOC.WAREHOUSEID
    AND L.STOREID=LOC.STOREID
    AND L.AISLE=LOC.AISLE
    AND L.UNDEF7=LOC.UNDEF7
    AND L.BAY=LOC.BAY
    AND L.LAYER<LOC.LAYER
  ) MARTIX_LAYER,
  (
    SELECT COUNT(DISTINCT L.BAY)||'-'||SUM(L.LENGTH)
    FROM LOCATIONS L
    WHERE L.WAREHOUSEID=LOC.WAREHOUSEID
    AND L.STOREID=LOC.STOREID
    AND L.AISLE=LOC.AISLE
    AND L.UNDEF7=LOC.UNDEF7
    AND L.LAYER=LOC.LAYER
    AND L.BAY<LOC.BAY    
  ) MARTIX_COLUMN,
  LOC.LENGTH WIDTH,
  LOC.HEIGHT,
  RTRIM(LOC.AISLE)||'.'||LPAD(LOC.BAY,3,'0')||'.'||LOC.LAYER||
    CASE WHEN LOC.RELATIVEBAY=0 THEN NULL ELSE ' ['||LOC.RELATIVEBAY||']' END LOCADDRESS,
  ITM.ITEMCODE,
  ITM.DESCR1 ITM_DESCR1,
  NVL(ITM.SERIALNOHANDLINGFLG,0) SERIALNOHANDLINGFLG,
  ITM.UNDEF4 SERIALLENGTH,
  ITM.UNDEF41 SERIALPREFIX,
  ITM.UNDEF28 ISDUAL,  
  V.PICKINGQTY,
  ITM.LU1PERLU2,
  ITM.IMAGEPATH,
  LUT.DESCR1 LUT_DESCR,
  ITM.LU1BARCODE||','||ITM.LU2BARCODE||','||(
      SELECT LISTAGG(SUI.BARCODE,',') WITHIN GROUP (ORDER BY SUI.BARCODE)
      FROM SUPPLIER_ITEMS SUI
      WHERE SUI.ITEMID=V.ITEMID
      AND RTRIM(SUI.BARCODE) IS NOT NULL
    ) BARCODES
FROM 
  ORDERS ORD,
  CUSTOMERS CUS,
  ORDDETS ODT,
  ORDANALS ODA,
  V_PICKING_1_2_3 V,
  LOCATIONS LOC,
  ITEMS ITM,
  LUTYPES LUT
WHERE V.PICKINGQTY>0
AND	ORD.ORDERID=:orderid
AND ORD.ORDERID=ODT.ORDERID
AND ORD.CUSTOMERID=CUS.CUSTOMERID
AND ODT.ORDDETID=ODA.ORDDETID
AND ODA.ORDANALID=V.ORDANALID
AND V.WAREHOUSEID=LOC.WAREHOUSEID
AND V.LOCATIONID=LOC.LOCATIONID
AND V.ITEMID=ITM.ITEMID
AND ITM.LU1ID=LUT.LUID(+)
ORDER BY LOCADDRESS