DECLARE
  P_TASKID		    TASKS.TASKID%TYPE:=TO_NULL(:pTaskId);
  P_ORDANALID		ORDANALS.ORDANALID%TYPE:=TO_NULL(:pOrdanalId);
  P_PICKINGTYPE	    V_PICKING_1_2_3.PICKINGTYPE%TYPE:=:pPickingType;
  P_ORDERSGROUP     ORDERSGROUPS.ORDERSGROUP%TYPE:=:pOrdersgroup;
  P_PREPACKAGEID    PREPACKAGES.PREPACKAGEID%TYPE:=TO_NULL(:pPrepackageid);
  P_WAREHOUSEID     WAREHOUSES.WAREHOUSEID%TYPE:=:pWarehouseid;
  P_LOCATIONID      LOCATIONS.LOCATIONID%TYPE:=:pLocationid;
  P_LU3BARCODE      LU3S.BARCODE%TYPE:=:pLu3barcode;
  P_ITEMID          ITEMS.ITEMID%TYPE:=:pItemid;
  P_STOCKSTATUSID   STOCKSTATUS.STOCKSTATUSID%TYPE:=:pStockstatusid;
  P_WMSSTATUSID     WMSSTATUS.WMSSTATUSID%TYPE:=:pWmsstatusid;
  P_REQ_LOTID       ORDANALS.LOTID%TYPE:=TO_NULL(:pReqLotid);
  P_LOTID		    LOTS.LOTID%TYPE:=TO_NULL(:pLotid);
  PT_STD            FD.PT_STOCKDETS;
  P_QTY		        ORDDETS.TOTALQTY%TYPE:=:pQty;
  P_SCANNEDBARCODE	ITEMS.UNDEF1%TYPE:=:pScannedBarcode;
BEGIN 
/*SrnUpdate*/
	TRACE_INFO.EMPLOYEEID:=:pPickerId;
	ORD_PICK_CNF(P_TASKID,P_ORDANALID,P_PICKINGTYPE,P_ORDERSGROUP,P_PREPACKAGEID,P_WAREHOUSEID,P_LOCATIONID,P_LU3BARCODE,P_ITEMID,P_STOCKSTATUSID,P_WMSSTATUSID,P_REQ_LOTID,P_LOTID,PT_STD,P_QTY,P_SCANNEDBARCODE);
END;